openapi: 3.0.2
info:
    title: Library-API
    version: 1.0.0
    description: '### This is a Swagger UI for our Library API'
paths:
    /users:
        get:
            tags:
                - users
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of users:
                                    value: |-
                                        [
                                            {id:1,firstname:"Jeff",lastname:"Bezos",email:"jeffbezos@amazon.com",password:"markzuckerbergsux",username:"bigbezos420",phonenr:"+1 11748794 "},
                                            {id:2,firstname:"Mark",lastname:"Zuckerberg",email:"markzuckerberg@facebook.com",password:"jeffbezossux",username:"markzuckofficial",phonenr:"+1 82543794 "}
                                        ]
                    description: Returns list of users
            summary: Get list of users
            description: Returns list of all users
        post:
            tags:
                - users
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                User created:
                                    value:
                                        id: 1
                                        firstname: Jeff
                                        lastname: Bezos
                                        email: jeffbezos@amazon.com
                                        password: markzuckerbergsux
                                        username: bigbezos420
                                        phonenr: +1 11748794
                    description: User created
            summary: Add new user
            description: |
                Returns created user
    /books:
        get:
            tags:
                - books
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/book'
                            examples:
                                List of books:
                                    value:
                                        -
                                            id: 1
                                            title: Romeo and Juliet
                                            author: William Shakespeare
                                            description: >-
                                                Romeo and Juliet, play by William Shakespeare, written about
                                                1594–96 and first published in an unauthorized quarto in 1597.
                                                An authorized quarto appeared in 1599, substantially longer
                                                and more reliable.
                                            releasedate: '1597'
                                            booklength: 480
                                            language: English
                                            price: 5.99
                                            pdf: '?'
                                        -
                                            id: 2
                                            title: 'Moby Dick; Or, The Whale'
                                            author: Herman Melville
                                            description: >-
                                                Moby-Dick; or, The Whale is an 1851 novel by American writer
                                                Herman Melville. The book is the sailor Ishmael's narrative of
                                                the maniacal quest of Ahab, captain of the whaling ship
                                                Pequod, for vengeance against Moby Dick, the giant white sperm
                                                whale that bit off his leg on the ship's previous voyage.
                                            releasedate: '1851'
                                            booklength: 378
                                            language: English
                                            price: 4.99
                                            pdf: '?'
                                        -
                                            id: 3
                                            title: A Room with a View
                                            author: E. M. Forster
                                            description: Romeo and Juliet
                                            releasedate: '1908'
                                            booklength: 321
                                            language: English
                                            price: 3.99
                                            pdf: '?'
                                        -
                                            id: 4
                                            title: Middlemarch
                                            author: '?'
                                            description: '?'
                                            releasedate: '?'
                                            booklength: '?'
                                            language: '?'
                                            price: '?'
                                            pdf: '?'
                                        -
                                            id: 5
                                            title: 'The Blue Castle: a novel'
                                            author: '?'
                                            description: '?'
                                            releasedate: '?'
                                            booklength: '?'
                                            language: '?'
                                            price: '?'
                                            pdf: '?'
                    description: >-
                        Returns an array of Books (id, title, author, description, releasedate, booklength,
                        language, price)
            summary: Get list of books
            description: Returns an array of Books
        post:
            requestBody:
                description: |-
                    {
                      "title": "Romeo and Juliet",
                      "author": "William Shakespeare",
                      "description": "Romeo and Juliet, play by William Shakespeare, written about 1594–96 and first published in an unauthorized quarto in 1597. An authorized quarto appeared in 1599, substantially longer and more reliable.",
                      "releasedate": "1597",
                      "booklength": 480,
                      "language": "English",
                      "price": 5.99,
                      "pdf": "?"
                    }
                required: true
            tags:
                - books
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/book'
                            examples:
                                Create new Book:
                                    value:
                                        id: 1
                                        title: Romeo and Juliet
                                        author: William Shakespeare
                                        description: >-
                                            Romeo and Juliet, play by William Shakespeare, written about
                                            1594–96 and first published in an unauthorized quarto in 1597. An
                                            authorized quarto appeared in 1599, substantially longer and more
                                            reliable.
                                        releasedate: '1597'
                                        booklength: 480
                                        language: English
                                        price: 5.99
                    description: >-
                        Returns created Book (id, title, author, description, releasedate, booklength,
                        language, price)
            operationId: /books/create
            summary: Add new Book
            description: Returns created Book
    '/users/{id}':
        get:
            tags:
                - users
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: string
                    description: Returns user
            operationId: id
            summary: Get details of a user
            description: Returns details of user
        put:
            requestBody: {}
            tags:
                - users
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                    description: Updates details
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
            summary: Update details of a user
            description: Updates details of user
        delete:
            tags:
                - users
            responses:
                '204':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
            description: Deletes user from database
        parameters:
            -
                name: id
                in: path
                required: true
    '/books/{id}':
        get:
            tags:
                - books
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/book'
                            examples:
                                Book:
                                    value:
                                        id: 1
                                        title: Romeo and Juliet
                                        author: William Shakespeare
                                        description: >-
                                            Romeo and Juliet, play by William Shakespeare, written about
                                            1594–96 and first published in an unauthorized quarto in 1597. An
                                            authorized quarto appeared in 1599, substantially longer and more
                                            reliable.
                                        releasedate: '1597'
                                        booklength: 480
                                        language: English
                                        price: 5.99
                    description: >-
                        Returns book by id (id, title, author, description, releasedate, booklength, language,
                        price)
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Not found.:
                                    value:
                                        error: book not found.
                    description: Returns error
            summary: Get one book
            description: Returns book by id
        put:
            requestBody:
                description: |-
                    {
                      "title": "Romeo and Juliet2",
                      "author": "William Shakespeare2",
                      "description": "A play by William Shakespeare, written about 1594–96 and first published in an unauthorized quarto in 1597. An authorized quarto appeared in 1599, substantially longer.",
                      "releasedate": "1597",
                      "booklength": 480,
                      "language": "English",
                      "price": 6.95,
                      "pdf": "?"
                    },
                required: true
            tags:
                - books
            responses:
                '200':
                    content:
                        text/xml:
                            examples:
                                Success:
                                    value: '"book updated successfully."'
                    description: OK
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                field is required:
                                    value: '{ error: "At least one field is required." }'
                    description: some fields are missing
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Not found:
                                    value: '{ error: "book not found." }'
                    description: book not found
            summary: Update book
            description: Updates book by id
        delete:
            tags:
                - books
            responses:
                '204':
                    description: No content
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Book not found.:
                                    value:
                                        error: book not found.
                    description: Book not found
            summary: Delete book by id
            description: Deletes book using its id
        parameters:
            -
                name: id
                schema:
                    type: integer
                in: path
                required: true
    /orders:
        get:
            tags:
                - orders
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/order'
                            examples:
                                all orders:
                                    value:
                                        -
                                            id: 1
                                            ordernr: ORDER-213337
                                            rentaldate: '2023-10-24'
                                            returndate: '2023-10-29'
                                            UserId: 1
                                            createdAt: '2023-10-24T20:26:35.000Z'
                                            updatedAt: '2023-10-24T20:26:35.000Z'
                                            User:
                                                id: 1
                                                firstname: Jeff1
                                                lastname: Bezos
                                                email: jeffbezos@amazon.com
                                                password: markzuckerbergsux
                                                username: bigbezos420
                                                phonenr: +1 11748794
                                                createdAt: '2023-10-24T11:13:56.000Z'
                                                updatedAt: '2023-10-24T11:13:56.000Z'
                                            OrderItems:
                                                -
                                                    id: 1
                                                    OrderId: 1
                                                    BookId: 1
                                                    createdAt: '2023-10-24T20:26:35.000Z'
                                                    updatedAt: '2023-10-24T20:26:35.000Z'
                                                    Book:
                                                        id: 1
                                                        title: Among Us 1
                                                        author: William Shakespeare2
                                                        description: >-
                                                            Romeo and Juliet, play by William Shakespeare,
                                                            written about 1594–96 and first published in an
                                                            unauthorized quarto in 1597. An authorized quarto
                                                            appeared in 1599, substantially longer and more
                                                            reliable.
                                                        releasedate: '1597-01-01T00:00:00.000Z'
                                                        booklength: 480
                                                        language: English
                                                        price: 5.99
                                                        createdAt: '2023-10-24T18:34:49.000Z'
                                                        updatedAt: '2023-10-24T18:34:49.000Z'
                                                -
                                                    id: 2
                                                    OrderId: 1
                                                    BookId: 2
                                                    createdAt: '2023-10-24T20:26:35.000Z'
                                                    updatedAt: '2023-10-24T20:26:35.000Z'
                                                    Book:
                                                        id: 2
                                                        title: Among Us 2
                                                        author: William Shakespeare2
                                                        description: >-
                                                            Romeo and Juliet, play by William Shakespeare,
                                                            written about 1594–96 and first published in an
                                                            unauthorized quarto in 1597. An authorized quarto
                                                            appeared in 1599, substantially longer and more
                                                            reliable.
                                                        releasedate: '1597-01-01T00:00:00.000Z'
                                                        booklength: 480
                                                        language: English
                                                        price: 5.99
                                                        createdAt: '2023-10-24T18:34:51.000Z'
                                                        updatedAt: '2023-10-24T18:34:51.000Z'
                                                -
                                                    id: 3
                                                    OrderId: 1
                                                    BookId: 3
                                                    createdAt: '2023-10-24T20:26:35.000Z'
                                                    updatedAt: '2023-10-24T20:26:35.000Z'
                                                    Book:
                                                        id: 3
                                                        title: Among Us 3
                                                        author: William Shakespeare2
                                                        description: >-
                                                            Romeo and Juliet, play by William Shakespeare,
                                                            written about 1594–96 and first published in an
                                                            unauthorized quarto in 1597. An authorized quarto
                                                            appeared in 1599, substantially longer and more
                                                            reliable.
                                                        releasedate: '1597-01-01T00:00:00.000Z'
                                                        booklength: 480
                                                        language: English
                                                        price: 5.99
                                                        createdAt: '2023-10-24T18:34:55.000Z'
                                                        updatedAt: '2023-10-24T18:34:55.000Z'
                                        -
                                            id: 2
                                            ordernr: ORDER-545299
                                            rentaldate: '2023-10-24'
                                            returndate: '2023-10-29'
                                            UserId: 1
                                            createdAt: '2023-10-24T20:26:46.000Z'
                                            updatedAt: '2023-10-24T20:26:46.000Z'
                                            User:
                                                id: 1
                                                firstname: Jeff1
                                                lastname: Bezos
                                                email: jeffbezos@amazon.com
                                                password: markzuckerbergsux
                                                username: bigbezos420
                                                phonenr: +1 11748794
                                                createdAt: '2023-10-24T11:13:56.000Z'
                                                updatedAt: '2023-10-24T11:13:56.000Z'
                                            OrderItems:
                                                -
                                                    id: 4
                                                    OrderId: 2
                                                    BookId: 6
                                                    createdAt: '2023-10-24T20:26:46.000Z'
                                                    updatedAt: '2023-10-24T20:26:46.000Z'
                                                    Book:
                                                        id: 6
                                                        title: Title this
                                                        author: William Shakespeare2
                                                        description: >-
                                                            Romeo and Juliet, play by William Shakespeare,
                                                            written about 1594–96 and first published in an
                                                            unauthorized quarto in 1597. An authorized quarto
                                                            appeared in 1599, substantially longer and more
                                                            reliable.
                                                        releasedate: '1597-01-01T00:00:00.000Z'
                                                        booklength: 480
                                                        language: English
                                                        price: 11.99
                                                        createdAt: '2023-10-24T19:33:51.000Z'
                                                        updatedAt: '2023-10-24T19:33:51.000Z'
                                        -
                                            id: 3
                                            ordernr: ORDER-002970
                                            rentaldate: '2023-10-26'
                                            returndate: '2023-10-31'
                                            UserId: 5
                                            createdAt: '2023-10-26T05:10:09.000Z'
                                            updatedAt: '2023-10-26T05:10:09.000Z'
                                            User:
                                                id: 5
                                                firstname: TestUser123
                                                lastname: Bezos
                                                email: jeffbezos@amazon.com
                                                password: markzuckerbergsux
                                                username: bigbezos420
                                                phonenr: +1 11748794
                                                createdAt: '2023-10-26T05:08:56.000Z'
                                                updatedAt: '2023-10-26T05:08:56.000Z'
                                            OrderItems:
                                                -
                                                    id: 5
                                                    OrderId: 3
                                                    BookId: 1
                                                    createdAt: '2023-10-26T05:10:09.000Z'
                                                    updatedAt: '2023-10-26T05:10:09.000Z'
                                                    Book:
                                                        id: 1
                                                        title: Among Us 1
                                                        author: William Shakespeare2
                                                        description: >-
                                                            Romeo and Juliet, play by William Shakespeare,
                                                            written about 1594–96 and first published in an
                                                            unauthorized quarto in 1597. An authorized quarto
                                                            appeared in 1599, substantially longer and more
                                                            reliable.
                                                        releasedate: '1597-01-01T00:00:00.000Z'
                                                        booklength: 480
                                                        language: English
                                                        price: 5.99
                                                        createdAt: '2023-10-24T18:34:49.000Z'
                                                        updatedAt: '2023-10-24T18:34:49.000Z'
                                                -
                                                    id: 6
                                                    OrderId: 3
                                                    BookId: 2
                                                    createdAt: '2023-10-26T05:10:09.000Z'
                                                    updatedAt: '2023-10-26T05:10:09.000Z'
                                                    Book:
                                                        id: 2
                                                        title: Among Us 2
                                                        author: William Shakespeare2
                                                        description: >-
                                                            Romeo and Juliet, play by William Shakespeare,
                                                            written about 1594–96 and first published in an
                                                            unauthorized quarto in 1597. An authorized quarto
                                                            appeared in 1599, substantially longer and more
                                                            reliable.
                                                        releasedate: '1597-01-01T00:00:00.000Z'
                                                        booklength: 480
                                                        language: English
                                                        price: 5.99
                                                        createdAt: '2023-10-24T18:34:51.000Z'
                                                        updatedAt: '2023-10-24T18:34:51.000Z'
                                                -
                                                    id: 7
                                                    OrderId: 3
                                                    BookId: 3
                                                    createdAt: '2023-10-26T05:10:09.000Z'
                                                    updatedAt: '2023-10-26T05:10:09.000Z'
                                                    Book:
                                                        id: 3
                                                        title: Among Us 3
                                                        author: William Shakespeare2
                                                        description: >-
                                                            Romeo and Juliet, play by William Shakespeare,
                                                            written about 1594–96 and first published in an
                                                            unauthorized quarto in 1597. An authorized quarto
                                                            appeared in 1599, substantially longer and more
                                                            reliable.
                                                        releasedate: '1597-01-01T00:00:00.000Z'
                                                        booklength: 480
                                                        language: English
                                                        price: 5.99
                                                        createdAt: '2023-10-24T18:34:55.000Z'
                                                        updatedAt: '2023-10-24T18:34:55.000Z'
                    description: >-
                        Returns an array of Orders (id, ordernr, rentaldate, returndate, userId, User,
                        OrderItems)
            summary: Get list of orders
            description: Returns an array of Orders
        post:
            requestBody:
                description: |-
                    {
                        "bookIds": [7,8,9,10],
                        "userId": 1
                    }
                required: true
            tags:
                - orders
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/order'
                            examples:
                                Create new Order:
                                    value:
                                        id: 2
                                        ordernr: ORDER-545300
                                        rentaldate: '2023-10-24'
                                        returndate: '2023-10-29'
                                        UserId: 6
                                        createdAt: '2023-10-24T20:26:46.000Z'
                                        updatedAt: '2023-10-26T08:48:54.000Z'
                    description: 'Returns created Order (id, ordernr, rentaldate, returndate, UserId)'
            summary: Add new Order
            description: Returns created Order
    '/orders/{id}':
        get:
            tags:
                - orders
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/order'
                            examples:
                                example order:
                                    value:
                                        id: 2
                                        ordernr: ORDER-545300
                                        rentaldate: '2023-10-24'
                                        returndate: '2023-10-29'
                                        UserId: 6
                                        createdAt: '2023-10-24T20:26:46.000Z'
                                        updatedAt: '2023-10-26T08:48:54.000Z'
                                        User:
                                            id: 6
                                            firstname: Jan-Marcus
                                            lastname: Sivadi
                                            email: jmarcus.sivadi@gmail.com
                                            password: password123?
                                            username: JMS
                                            phonenr: +372 58803477
                                            createdAt: '2023-10-26T08:48:44.000Z'
                                            updatedAt: '2023-10-26T08:48:44.000Z'
                                        OrderItems:
                                            -
                                                id: 4
                                                OrderId: 2
                                                BookId: 6
                                                createdAt: '2023-10-24T20:26:46.000Z'
                                                updatedAt: '2023-10-24T20:26:46.000Z'
                                                Book:
                                                    id: 6
                                                    title: Title this
                                                    author: William Shakespeare2
                                                    description: >-
                                                        Romeo and Juliet, play by William Shakespeare, written
                                                        about 1594–96 and first published in an unauthorized
                                                        quarto in 1597. An authorized quarto appeared in 1599,
                                                        substantially longer and more reliable.
                                                    releasedate: '1597-01-01T00:00:00.000Z'
                                                    booklength: 480
                                                    language: English
                                                    price: 11.99
                                                    createdAt: '2023-10-24T19:33:51.000Z'
                                                    updatedAt: '2023-10-24T19:33:51.000Z'
                    description: 'Returns order by id (id, ordernr, rentaldate, returndate, UserId, User, OrderItems)'
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Not found.:
                                    value:
                                        error: order not found.
                    description: Returns error
            summary: Get one order
            description: Returns order by id
        put:
            requestBody:
                description: |-
                    {
                        "ordernr": "ORDER-1234",
                        "rentaldate": "1987-05-02",
                        "returndate": "1987-05-12"
                        "UserId": 4
                    }
                required: true
            tags:
                - orders
            responses:
                '200':
                    content:
                        application/json:
                            examples:
                                update success:
                                    value: '"order updated successfully."'
                    description: OK
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                field is required:
                                    value: '{ error: "At least one field is required." }'
                    description: some fields are missing
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                order not found:
                                    value: '{ error: "order not found." }'
                                user not found:
                                    value: '{ error: "user not found." }'
                                could not update order:
                                    value: '{ error: "could not update order" }'
                    description: not found.
            summary: Update order
            description: Updates order by id
        delete:
            tags:
                - orders
            responses:
                '204':
                    description: No content
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                order does not exist:
                                    value: '{ error: "Order not found." }'
                    description: Order not found
            summary: Delete order by id
            description: Deletes order using its id
components:
    schemas:
        error:
            title: Root Type for error
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: Error message.
        user:
            title: Root Type for user
            description: ''
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                firstname:
                    type: string
                lastname:
                    type: string
                email:
                    type: string
                password:
                    type: string
                username:
                    type: string
                phonenr:
                    type: string
            example:
                id: 1
                firstname: Jeff
                lastname: Bezos
                email: jeffbezos@amazon.com
                password: markzuckerbergsux
                username: bigbezos420
                phonenr: +1 11748794
        book:
            title: Root Type for book
            description: book entity
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                title:
                    type: string
                author:
                    type: string
                description:
                    type: string
                releasedate:
                    type: string
                booklength:
                    format: int32
                    type: integer
                language:
                    type: string
                price:
                    format: double
                    type: number
                pdf:
                    type: string
            example:
                id: 1
                title: Romeo and Juliet
                author: William Shakespeare
                description: >-
                    Romeo and Juliet, play by William Shakespeare, written about 1594–96 and first published
                    in an unauthorized quarto in 1597. An authorized quarto appeared in 1599, substantially
                    longer and more reliable.
                releasedate: '1597'
                booklength: 480
                language: English
                price: 5.99
                pdf: '?'
        order:
            title: Root Type for order
            description: ''
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                ordernr:
                    type: string
                rentaldate:
                    format: date
                    type: string
                returndate:
                    format: date
                    type: string
                UserId:
                    format: int32
                    type: integer
                createdAt:
                    format: date-time
                    type: string
                updatedAt:
                    format: date-time
                    type: string
                User:
                    type: object
                    properties:
                        id:
                            format: int32
                            type: integer
                        firstname:
                            type: string
                        lastname:
                            type: string
                        email:
                            type: string
                        password:
                            type: string
                        username:
                            type: string
                        phonenr:
                            type: string
                        createdAt:
                            format: date-time
                            type: string
                        updatedAt:
                            format: date-time
                            type: string
                OrderItems:
                    type: array
                    items:
                        type: object
                        properties:
                            id:
                                format: int32
                                type: integer
                            OrderId:
                                format: int32
                                type: integer
                            BookId:
                                format: int32
                                type: integer
                            createdAt:
                                format: date-time
                                type: string
                            updatedAt:
                                format: date-time
                                type: string
                            Book:
                                type: object
                                properties:
                                    id:
                                        format: int32
                                        type: integer
                                    title:
                                        type: string
                                    author:
                                        type: string
                                    description:
                                        type: string
                                    releasedate:
                                        format: date-time
                                        type: string
                                    booklength:
                                        format: int32
                                        type: integer
                                    language:
                                        type: string
                                    price:
                                        format: double
                                        type: number
                                    createdAt:
                                        format: date-time
                                        type: string
                                    updatedAt:
                                        format: date-time
                                        type: string
            example:
                id: 1
                ordernr: ORDER-213337
                rentaldate: '2023-10-24'
                returndate: '2023-10-29'
                UserId: 1
                createdAt: '2023-10-24T20:26:35.000Z'
                updatedAt: '2023-10-24T20:26:35.000Z'
                User:
                    id: 1
                    firstname: Jeff1
                    lastname: Bezos
                    email: jeffbezos@amazon.com
                    password: markzuckerbergsux
                    username: bigbezos420
                    phonenr: +1 11748794
                    createdAt: '2023-10-24T11:13:56.000Z'
                    updatedAt: '2023-10-24T11:13:56.000Z'
                OrderItems:
                    -
                        id: 1
                        OrderId: 1
                        BookId: 1
                        createdAt: '2023-10-24T20:26:35.000Z'
                        updatedAt: '2023-10-24T20:26:35.000Z'
                        Book:
                            id: 1
                            title: Among Us 1
                            author: William Shakespeare2
                            description: >-
                                Romeo and Juliet, play by William Shakespeare, written about 1594–96 and first
                                published in an unauthorized quarto in 1597. An authorized quarto appeared in
                                1599, substantially longer and more reliable.
                            releasedate: '1597-01-01T00:00:00.000Z'
                            booklength: 480
                            language: English
                            price: 5.99
                            createdAt: '2023-10-24T18:34:49.000Z'
                            updatedAt: '2023-10-24T18:34:49.000Z'
                    -
                        id: 2
                        OrderId: 1
                        BookId: 2
                        createdAt: '2023-10-24T20:26:35.000Z'
                        updatedAt: '2023-10-24T20:26:35.000Z'
                        Book:
                            id: 2
                            title: Among Us 2
                            author: William Shakespeare2
                            description: >-
                                Romeo and Juliet, play by William Shakespeare, written about 1594–96 and first
                                published in an unauthorized quarto in 1597. An authorized quarto appeared in
                                1599, substantially longer and more reliable.
                            releasedate: '1597-01-01T00:00:00.000Z'
                            booklength: 480
                            language: English
                            price: 5.99
                            createdAt: '2023-10-24T18:34:51.000Z'
                            updatedAt: '2023-10-24T18:34:51.000Z'
                    -
                        id: 3
                        OrderId: 1
                        BookId: 3
                        createdAt: '2023-10-24T20:26:35.000Z'
                        updatedAt: '2023-10-24T20:26:35.000Z'
                        Book:
                            id: 3
                            title: Among Us 3
                            author: William Shakespeare2
                            description: >-
                                Romeo and Juliet, play by William Shakespeare, written about 1594–96 and first
                                published in an unauthorized quarto in 1597. An authorized quarto appeared in
                                1599, substantially longer and more reliable.
                            releasedate: '1597-01-01T00:00:00.000Z'
                            booklength: 480
                            language: English
                            price: 5.99
                            createdAt: '2023-10-24T18:34:55.000Z'
                            updatedAt: '2023-10-24T18:34:55.000Z'
